BechaKeena/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from rest_framework_swagger.views import get_swagger_view
from apps import views


schema_view = get_swagger_view(title='Bechakena API v1')


urlpatterns = [
    path('', views.LogIn.as_view()),
    path('rest-auth', include('rest_framework.urls')),
    path('swagger/', schema_view),
    path('admin/', admin.site.urls),
    path('apps/', include('apps.urls')),
    path('apis/', include('apis.urls')),
]

apis/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^v1/', include('apis.v1.urls')),

]

pos/models.py
from django.db import models
from inventory.models import Product
from consumer.models import Device, COA
# Create your models here.

ORDER_STATUS = (
	('PENDING', 'PENDING'),
	('COMPLETED', 'COMPLETED'),
	('CANCELLED', 'CANCELLED')
)

INVOICE_STATUS = (
	('UNPAID', 'UNPAID'),
	('PAID', 'PAID'),
	('CARRY_FORWARD', 'CARRY_FORWARD')
)

class Order(models.Model):
    created_time = models.DateTimeField(auto_now=True)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    processed_time = models.DateTimeField(null=True, blank=True)
    processed_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='PENDING')
    order_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.pk)


class OrderLine(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unite_price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    dicount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.pk)


class Invoice(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    created_time = models.DateTimeField()
    processed_time = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=INVOICE_STATUS, default='UNPAID')
    total = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2)
    total_payable = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.pk)


class InvoiceLine(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unite_price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.pk)


class Transsection(models.Model):
    dabite_account = models.ForeignKey(COA, related_name='dabite_account')
    credite_account = models.ForeignKey(COA, related_name='credite_account')
    amount = models.DecimalField(max_digits=10, decimal_places=2)


class SalesReturn(models.Model):
    created_time = models.DateTimeField(auto_now=True)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    processed_time = models.DateTimeField(null=True, blank=True)
    processed_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='PENDING')
    order_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.pk)


class ReturnLine(models.Model):
    sales_return = models.ForeignKey(SalesReturn, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unite_price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    dicount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.pk)

apps/templates/apps/category_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Category Delete</h1>
    <form method="post">{% csrf_token %}
        <p>
            Are you sure you want to delete "{{ object }}" ?
        </p>
        <p>
            <input class="btn btn-primary" type="submit" value="Delete" />  <a href="{% url "category_list" %}" class="btn btn-danger">Cancel </a>
        </p>

    </form>
{% endblock %}

apps/templates/apps/category_form.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Category</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

apps/templates/apps/category_list.html
{% extends 'layout.html' %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Category List</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="col-md-12">
            <p>
                <a class="btn btn-primary" href="{% url "category_create" %}">Add New</a>
            </p>
        </div>
        <div class="col-md-12">
            <table class="table dataTable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Parent</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for category in object_list %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>{{ category.parent }}</td>
                    <th><a class="btn btn-default" href="{% url "category_edit" category.id %}">Edit</a></th>
            {#    <td></td>#}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
    $('.dataTable').DataTable();
} );
    </script>
{% endblock %}

apps/templates/apps/change_password.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Change Password</h1>
    <form method="post">{% csrf_token %}
        <p>
             <input type="password" class="form-control" name="password" placeholder="Current Password" required="" />
        </p>
        <p>
            <input type="password" class="form-control" name="new_password" placeholder="Password" required=""/>
        </p>
        <p>
            <input class="btn btn-lg btn-block" type="submit"></input>
        </p>
    </form>
{% endblock %}

apps/templates/apps/dashboard.html
{% extends "layout.html" %}
{% load staticfiles %}


{% block content %}
<div class="row">
	<h1>Hello Html</h1>
</div>

{% endblock %}

apps/templates/apps/device_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
    <h1>App User Delete</h1>
    <form method="post">{% csrf_token %}
        <p>
            Are you sure you want to delete "{{ object }}" ?
        </p>
        <p>
            <input class="btn btn-primary" type="submit" value="Delete" />  <a href="{% url "device_list" %}" class="btn btn-danger">Cancel </a>
        </p>

    </form>
{% endblock %}

apps/templates/apps/device_form.html
{% extends 'layout.html' %}

{% block content %}
    <h1>App User</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

apps/templates/apps/device_list.html
{% extends 'layout.html' %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">App User List</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="col-md-12">
            <table class="table dataTable">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>User Name</th>
                    <th>Shop Name</th>
                    <th>Address</th>
                    <th>SR No</th>
                    <th>Install Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for device in object_list %}
                <tr>
                    <td>{{ device.id }}</td>
                    <td>{{ device.user.username }}</td>
                    <td>{{ device.shop_name }}</td>
                    <td>{{ device.address }}</td>
                    <td>{{ device.sr_no }}</td>
                    <td>{{ device.install_date }}</td>
                    <th><a class="btn btn-warning" href="{% url 'device_reset_pin' device.pk %}">Reset Pin</a> <a class="btn btn-primary" href="{% url "device_edit" device.id %}">Edit</a> <a class="btn btn-danger" href="{% url "device_delete" device.id %}">Delete</a></th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
    $('.dataTable').DataTable({
        "order": [[ 0, "desc" ]]
    });
} );
    </script>
{% endblock %}

apps/templates/apps/login.html
{% extends 'login_layout.html' %}
{% load staticfiles %}
{% block extracss %}
<style type="text/css">
html, body {
    width: 100%;
    height: 100%;
  }

    .super-admin-wrap {
      position: relative;
      background-image: url('{% static "apps/images/imgpsh_fullsize.jpeg" %}');
      background-position: center center;
      background-repeat: no-repeat;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      height: 100%;
      width: 100%;
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }

      .form-signin {
        max-width: 280px;
        margin: 10px auto;
      }

      .form-signin .checkbox {
        font-weight: normal;
      }

      .form-signin .form-control {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
      }

      .form-signin input[type="text"] {
        margin-bottom: -1px;
        border-top: 1px solid transparent;
        border-right: 1px solid transparent;
        border-left: 1px solid transparent;
        box-shadow: none;
        border-radius: 3px 3px 0px 0px;
      }

      .form-signin input[type="text"]:focus {
        /*box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);*/
      }

      .form-signin input[type="password"] {
        z-index: 2;
        margin-bottom: 20px;
        border-top: none;
        border-bottom: 1px solid transparent;
        border-right: 1px solid transparent;
        border-left: 1px solid transparent;
        border-radius: 0px 0px 3px 3px;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
      }

      .form-signin input[type="password"]:focus {
        /*box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0px 1px 0px 0px rgba(255, 255, 255, 0.5);*/
      }

    .form-signin input[type="submit"] {
        z-index: 2;
        margin-bottom: 20px;
        border-top: none;
        border-bottom: 1px solid transparent;
        border-right: 1px solid transparent;
        border-left: 1px solid transparent;
        border-radius: 0px 0px 3px 3px;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
      }

    .form-signin input[type="submit"]:focus {
        /*box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0px 1px 0px 0px rgba(255, 255, 255, 0.5);*/
      }



</style>
{% endblock %}


{% block content %}
<div class="super-admin-wrap">
  <div class="container relative">
    {% if messages %}
    {% for message in messages %}
    <h3 class="{{ message.tags }}">{{ message }}</h3>
    {% endfor %}
{% endif %}
    <form action="" method="post" class="form-signin">
      <h3 style="color: #fff;">Admin Log In</h3>
    <div class="form-error">
        <span style="color: red;">{{ error }}</span>
    </div>
        <p>
            {{ message }}
        </p>
        {% csrf_token %}
          <input type="text" class="form-control" name="username" placeholder="Email Address" required="" autofocus="" />
          <input type="password" class="form-control" name="password" placeholder="Password" required=""/>

          <input class="btn btn-lg btn-block" type="submit">Log in</input>
      </form>
  </div>
</div>
{% endblock %}

apps/templates/apps/order_detail.html
{% extends 'layout.html' %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-print-12">
            <h1 class="text-center">বেচা-কেনা</h1>
            <h3 class="text-center">মহাজন এখন একটাই</h3>
            <br/>
            <br/>
            <div class="col-md-6 col-print-6">
                 <p><strong>ক্রেতার নাম:</strong> {{ order.device.shop_name }}</p>
                <p><strong>ঠিকানা:</strong> {{ order.device.address }}</p>
                <p><strong>মোবাইল নম্বর:</strong> {{ order.device.user.username }}</p>
            </div>
            <div class="col-md-6 col-print-6 text-right">
                <p><strong>ইনভয়েস নম্বর:</strong> {{ order.id }}</p>
                <p><strong>হটলাইন:</strong> 01885995100-02</p>
            </div>
        </div>

    </div>
    <div class="row">
    <div class="col-md-12 col-print-12">
        <table class="table">
        <tr>
            <th>সংখ্যা</th>
            <th>বিবরণ</th>
            <th>পরিমান</th>
            <th>একক</th>
            <th>টাকা</th>
            <th>মোট</th>
        </tr>
            {% for line in order.orderline_set.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ line.product.name }}</td>
                    <td>{{ line.quantity }}</td>
                    <td>{{ line.product.unite }}</td>
                    <td>{{ line.unite_price }}</td>
                    <td>{{ line.amount }}</td>
                </tr>
             {% endfor %}
        <tr>
            <td colspan="5">মোট</td>
            <td>{{ order.order_total }}</td>
        </tr>
        </table>
    <div class="col-md-12 col-print-12">
        <div class="col-md-6 col-print-6">ক্রেতার সাক্ষর:</div>
        <div class="col-md-6 col-print-6 text-right">বিক্রেতার সাক্ষর: </div>
    </div>
        <div class="col-md-12">
             <button class="btn btn-primary hidden-print" onclick="printFunction()"><span class="glyphicon glyphicon-print" aria-hidden="true"></span> Print</button>
        </div>
    </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
            $('.dataTable').DataTable();
        } );
        function printFunction() {
            window.print();
        }
    </script>
{% endblock %}

apps/templates/apps/order_list.html
{% extends 'layout.html' %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Order List</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="col-md-12">
            <table class="table dataTable">
            <thead>
                <tr>
                    <th>Order Id</th>
                    <th>Total</th>
                    <th>Shop Name</th>
                    <th>Order Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for order in object_list %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.order_total }}</td>
                    <td>{{ order.device.shop_name }}</td>
                    <td>{{ order.created_time }}</td>
                    <td>{{ order.status }}</td>
                    <th><a class="btn btn-default" href="{% url "order_details" order.id %}">View</a> <a class="btn btn-primary" {% if order.action_button_disable %}disabled {% endif %} href="{% url "order_complete" order.id %}">Complete</a></a> <a class="btn btn-danger" {% if order.action_button_disable %}disabled {% endif %} href="{% url "order_cancel" order.id %}">Cancel</a></th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
    $('.dataTable').DataTable({
        "order": [[ 0, "desc" ]]
    });
} );
    </script>
{% endblock %}

apps/templates/apps/product_confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Product Delete</h1>
    <form method="post">{% csrf_token %}
        <p>
            Are you sure you want to delete "{{ object }}" ?
        </p>
        <p>
            <input class="btn btn-primary" type="submit" value="Delete" />  <a href="{% url "category_list" %}" class="btn btn-danger">Cancel </a>
        </p>

    </form>
{% endblock %}

apps/templates/apps/product_form.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Product</h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

apps/templates/apps/product_list.html
{% extends 'layout.html' %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Product List</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="col-md-12">
            <p>
                <a class="btn btn-primary" href="{% url "product_create" %}">Add New</a>
            </p>
        </div>
        <div class="col-md-12">
            <table class="table dataTable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for product in object_list %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.price }}</td>
                    <th><a class="btn btn-default" href="{% url "product_edit" product.id %}">Edit</a></th>
            {#    <td></td>#}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
    $('.dataTable').DataTable();
} );
    </script>
{% endblock %}